name: medovuha ci
on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    container: python:3.8-slim
    steps:
      - uses: actions/checkout@v2
      - working-directory: python
      - run: |
          pip install flake8
          flake8

  test:
    needs: lint
    runs-on: ubuntu-latest
    container: python:3.8-slim
    steps:
      - uses: actions/checkout@v2
      - working-directory: python
      - run: |
          pip install -e ./[dev]
          pytest

